{% set version = "1.2.6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-boomspikeslab
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/BoomSpikeSlab_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/BoomSpikeSlab/BoomSpikeSlab_{{ version }}.tar.gz
  sha256: 87f622e20f13c255da5ea65b7bf07467cca5733184dc4ad4fd134c88cc72c63e

build:
  # Checking windows to see if it passes. Uncomment the line if it fails.
  # skip: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-boom >=0.9.13
  run:
    - r-base
    - r-boom >=0.9.13

test:
  commands:
    - $R -e "library('BoomSpikeSlab')"           # [not win]
    - "\"%R%\" -e \"library('BoomSpikeSlab')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=BoomSpikeSlab
  license: LGPL-2.1-only
  summary: Spike and slab regression with a variety of residual error distributions corresponding to Gaussian, Student T, probit, logit, SVM, and a few others.  Spike and slab regression is Bayesian regression with prior distributions containing a point mass at zero.  The posterior updates the amount of mass on this point,
    leading to a posterior distribution that is actually sparse, in the sense that if you sample from it many coefficients are actually zeros.  Sampling from this posterior distribution is an elegant way to handle Bayesian variable selection and model averaging.  See <DOI:10.1504/IJMMNO.2014.059942> for an explanation of
    the Gaussian case.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-2.1
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - Yue-Li-atBain
